<?php
// This script and data application were generated by AppGini 5.40
// Download AppGini for free from http://bigprof.com/appgini/download/

	$currDir=dirname(__FILE__);
	include("$currDir/defaultLang.php");
	include("$currDir/language.php");
	include("$currDir/lib.php");
	@include("$currDir/hooks/external_entity.php");
	include("$currDir/external_entity_dml.php");

	// mm: can the current member access this page?
	$perm=getTablePermissions('external_entity');
	if(!$perm[0]){
		echo error_message($Translation['tableAccessDenied'], false);
		echo '<script>setTimeout("window.location=\'index.php?signOut=1\'", 2000);</script>';
		exit;
	}

	$x = new DataList;
	$x->TableName = "external_entity";

	// Fields that can be displayed in the table view
	$x->QueryFieldsTV=array(   
		"`external_entity`.`id`" => "id",
		"`external_entity`.`company_name`" => "company_name",
		"`external_entity`.`company_class`" => "company_class",
		"`external_entity`.`primary_email`" => "primary_email",
		"`external_entity`.`alternate_email`" => "alternate_email",
		"CONCAT_WS('-', LEFT(`esternal_entity`.`phone`,3), MID(`esternal_entity`.`phone`,4,3), RIGHT(`esternal_entity`.`phone`,4))" => "phone",
		"`esternal_entity`.`country`" => "country",
		"`esternal_entity`.`street`" => "street",
		"`esternal_entity`.`city`" => "city",
		"`esternal_entity`.`zip`" => "zip",
		"`esternal_entity`.`comments`" => "comments"
	);
	// mapping incoming sort by requests to actual query fields
	$x->SortFields = array(   
		1 => '`external_entity`.`id`',
		2 => '`external_entity`.`company_name`',
		3 => '`external_entity`.`company_class`',
		4 => 4,
		5 => 5,
		6 => '`external_entity`.`phone`',
		7 => 7,
		8 => 8,
		9 => 9,
		10 => 10,
		11 => 11,
		
	);

	// Fields that can be displayed in the csv file
	$x->QueryFieldsCSV=array(   
		"`external_entity`.`id`" => "id",
		"`external_entity`.`company_name`" => "company_name",
		"`external_entity`.`company_class`" => "company_class",
		"`external_entity`.`primary_email`" => "primary_email",
		"`external_entity`.`alternate_email`" => "alternate_email",
		"CONCAT_WS('-', LEFT(`esternal_entity`.`phone`,3), MID(`esternal_entity`.`phone`,4,3), RIGHT(`esternal_entity`.`phone`,4))" => "phone",
		"`esternal_entity`.`country`" => "country",
		"`esternal_entity`.`street`" => "street",
		"`esternal_entity`.`city`" => "city",
		"`esternal_entity`.`zip`" => "zip",
		"`esternal_entity`.`comments`" => "comments"
	);
	// Fields that can be filtered
	$x->QueryFieldsFilters=array( 
		"`external_entity`.`id`" => "ID",
		"`external_entity`.`company_name`" => "Company name",
		"`external_entity`.`company_class`" => "Company class",
		"`external_entity`.`primary_email`" => "Primary email",
		"`external_entity`.`alternate_email`" => "Alternate email",
		 "`esternal_entity`.`phone`"=> "phone",
		"`esternal_entity`.`country`" => "country",
		"`esternal_entity`.`street`" => "street",
		"`esternal_entity`.`city`" => "city",
		"`esternal_entity`.`zip`" => "zip",
		"`esternal_entity`.`comments`" => "comments"
	);

	// Fields that can be quick searched
	$x->QueryFieldsQS=array(   
		"`external_entity`.`id`" => "id",
		"`external_entity`.`company_name`" => "company_name",
		"`external_entity`.`company_class`" => "company_class",
		"`external_entity`.`primary_email`" => "primary_email",
		"`esternal_entity`.`alternate_email`" => "alternate_email",
		"CONCAT_WS('-', LEFT(`esternal_entity`.`phone`,3), MID(`esternal_entity`.`phone`,4,3), RIGHT(`esternal_entity`.`phone`,4))" => "phone",
		"`esternal_entity`.`country`" => "country",
		"`esternal_entity`.`street`" => "street",
		"`esternal_entity`.`city`" => "city",
		"`esternal_entity`.`zip`" => "zip",
		"`esternal_entity`.`comments`" => "comments"
	);

	// Lookup fields that can be used as filterers
	$x->filterers = array();

	$x->QueryFrom="`external_entity` ";
	$x->QueryWhere='';
	$x->QueryOrder='';

	$x->AllowSelection = 1;
	$x->HideTableView = ($perm[2]==0 ? 1 : 0);
	$x->AllowDelete = $perm[4];
	$x->AllowMassDelete = false;
	$x->AllowInsert = $perm[1];
	$x->AllowUpdate = $perm[3];
	$x->SeparateDV = 1;
	$x->AllowDeleteOfParents = 0;
	$x->AllowFilters = 1;
	$x->AllowSavingFilters = 0;
	$x->AllowSorting = 1;
	$x->AllowNavigation = 1;
	$x->AllowPrinting = 1;
	$x->AllowCSV = 1;
	$x->RecordsPerPage = 10;
	$x->QuickSearch = 1;
	$x->QuickSearchText = $Translation["quick search"];
	$x->ScriptFileName = "external_entity_view.php";
	$x->RedirectAfterInsert = "external_entity_view.php?SelectedID=#ID#";
	$x->TableTitle = "External entities";
	$x->TableIcon = "resources/table_icons/account_balances.png";
	$x->PrimaryKey = "`external_entity`.`id`";
	$x->DefaultSortField = '2';
	$x->DefaultSortDirection = 'asc';

	$x->ColWidth   = array(  100, 100, 100, 100, 100, 100, 80, 80, 80, 100, 100);
	$x->ColCaption = array("Company name", "Company class", "Primary email","Alternate email", "Phone", "Country", "street", "City", "Zip", "Comments");
	$x->ColFieldName = array('company_name', 'company_class', 'primary_email', 'alternate_email', 'phone', 'country', 'street', 'city', 'zip', 'comments');
	$x->ColNumber  = array(2, 3, 4, 5, 6, 7, 10, 11);

	$x->Template = 'templates/external_entity_templateTV.html';
	$x->SelectedTemplate = 'templates/external_entity_templateTVS.html';
	$x->ShowTableHeader = 1;
	$x->ShowRecordSlots = 0;
	$x->HighlightColor = '#FFF0C2';

	// mm: build the query based on current member's permissions
	$DisplayRecords = $_REQUEST['DisplayRecords'];
	if(!in_array($DisplayRecords, array('user', 'group'))){ $DisplayRecords = 'all'; }
	if($perm[2]==1 || ($perm[2]>1 && $DisplayRecords=='user' && !$_REQUEST['NoFilter_x'])){ // view owner only
		$x->QueryFrom.=', membership_userrecords';
		$x->QueryWhere="where `external_entity`.`id`=membership_userrecords.pkValue and membership_userrecords.tableName='external_entity' and lcase(membership_userrecords.memberID)='".getLoggedMemberID()."'";
	}elseif($perm[2]==2 || ($perm[2]>2 && $DisplayRecords=='group' && !$_REQUEST['NoFilter_x'])){ // view group only
		$x->QueryFrom.=', membership_userrecords';
		$x->QueryWhere="where `external_entity`.`id`=membership_userrecords.pkValue and membership_userrecords.tableName='external_entity' and membership_userrecords.groupID='".getLoggedGroupID()."'";
	}elseif($perm[2]==3){ // view all
		// no further action
	}elseif($perm[2]==0){ // view none
		$x->QueryFields = array("Not enough permissions" => "NEP");
		$x->QueryFrom = '`external_entity`';
		$x->QueryWhere = '';
		$x->DefaultSortField = '';
	}
	// hook: external_entity_init
	$render=TRUE;
	if(function_exists('external_entity_init')){
		$args=array();
		$render=external_entity_init($x, getMemberInfo(), $args);
	}

	if($render) $x->Render();

	// hook: external_entity_header
	$headerCode='';
	if(function_exists('external_entity_header')){
		$args=array();
		$headerCode=external_entity_header($x->ContentType, getMemberInfo(), $args);
	}  
	if(!$headerCode){
		include_once("$currDir/header.php"); 
	}else{
		ob_start(); include_once("$currDir/header.php"); $dHeader=ob_get_contents(); ob_end_clean();
		echo str_replace('<%%HEADER%%>', $dHeader, $headerCode);
	}

	echo $x->HTML;
	// hook: external_entity_footer
	$footerCode='';
	if(function_exists('external_entity_footer')){
		$args=array();
		$footerCode=external_entity_footer($x->ContentType, getMemberInfo(), $args);
	}  
	if(!$footerCode){
		include_once("$currDir/footer.php"); 
	}else{
		ob_start(); include_once("$currDir/footer.php"); $dFooter=ob_get_contents(); ob_end_clean();
		echo str_replace('<%%FOOTER%%>', $dFooter, $footerCode);
	}
?>